apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-datascience
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: charts/onboard-datascience
    repoURL: 'https://github.com/alpha-hack-program/fraud-detection-mlops.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../../gitops/values-common.yaml
      - ../../gitops/onboard-datascience/values-datasciene.yaml
     parameters:
      - name: "github.token"
        value: "changeme_token"
      - name: "github.user"
        value: "changeme_user"    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true