apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-inference
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: charts/inference
    repoURL: 'https://github.com/alpha-hack-program/fraud-detection-mlops.git'
    targetRevision: init #TODO HEAD
    helm:
      valueFiles:
      - ../../gitops/values-common.yaml
      - ../../gitops/inference/values-inference.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true