kind: Secret
apiVersion: v1
metadata:
  name: github-token
  namespace: {{ $.Values.project.name }}
  annotations:
    tekton.dev/git-0: 'https://github.com/{{ .Values.pipeline.github.user }}'
data:
  password: {{ .Values.pipeline.github.token | b64enc | quote }}
  username: {{ .Values.pipeline.github.user | b64enc | quote }}
type: kubernetes.io/basic-auth