---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: {{ $.Values.project.name }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
secrets:
  - name: github-token